




GET  http://localhost:5000/home HTTP/1.1
content-type: application/json

###

GET  http://localhost:5000/dashboard HTTP/1.1
content-type: application/json

###

POST  http://localhost:5000/users/login HTTP/1.1
content-type: application/json

{
    "email" : "abbass1@gmail.com",
    "password" : "Password123"    
}

###

POST  http://localhost:5000/users/register HTTP/1.1
content-type: application/json

{
    "name" : "abbass",
    "email" : "abbass3@gmail.com",
    "password" : "Password123"    
}

###

POST  http://localhost:5000/users/logout HTTP/1.1
content-type: application/json